# HTTP Server.
server:
  address: ":8000"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:123456@tcp(118.195.238.77:3306)/wesoul"
    debug: true

# redis
redis:
  default:
    host: 127.0.0.1:6379
    password:
    database: 0

# 上链
chain:
  appId: 5
  appSecret: eX3wKQtKuYrQItryXsjYUXhr
  tokenUrl: https://localhost:8111/blockchain/metadata/%s/%s
  upChainUrl: http://47.93.32.136:8881/api/batch/tokens
  chainAddr: 0xc1dcca2d749a1e6ae916dde24fcf3b5742d64098

#sms配置
sms:
  url: "https://market.juncdt.com/smartmarket/msgService/sendMessage"
  accessKey: "d0ad7a519058866cb5"
  accessSecret: "f27ee1886f933516ffb01d4bb6407f"
  classificationSecret: "2atbqWLP"
  signCode: "EHf3xALg"
  templateCode: "AqY0bsaM"

system:
  #env: test
