# HTTP Server.
server:
  address: ":8000"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:Wesoul@123@tcp(101.200.209.201:3306)/wesoul"
    debug: true

# redis
redis:
  default:
    address: 127.0.0.1:6379
    pass: RD85d9o5P
    database: 0

# 上链
chain:
  name: "国广链"
  appId: 5
  appSecret: eX3wKQtKuYrQItryXsjYUXhr
  tokenUrl: http://47.96.131.64:8000/blockchain/metadata/%s/%s
  upChainUrl: http://47.93.32.136:8881/api/batch/tokens
  chainAddr: 0xc1dcca2d749a1e6ae916dde24fcf3b5742d64098

#sms配置
sms:
  url: "https://market.juncdt.com/smartmarket/msgService/sendMessage"
  accessKey: "d0ad7a519058866cb5"
  accessSecret: "f27ee1886f933516ffb01d4bb6407f"
  classificationSecret: "2atbqWLP"
  signCode: "EHf3xALg"
  templateCode: "AqY0bsaM"

system:
  #env: test

# upload
upload:
    bucket: "megahero-website"
    accessKey: "KqGLoHVvPUziQtdocS0mk7FhI2lcw7oNt93GfGuU"
    secretKey: "3ZrQQmzgC6svX8_3Dy5WJi0DdSAnGRr3kPkKIsj8"
    cdn: "https://website-cdn.gfanx.com/"

# define
define:
  didImg: "https://website-cdn.gfanx.com/did/c9c87cbb-f208-4b49-a38a-cd5e519d91a2.jpeg"
  wesoulUid: "121a016c3d1e4s5d9c85b1a898f623s1"
