// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Endorse is the golang structure of table endorse for DAO operations like Where/Data.
type Endorse struct {
	g.Meta    `orm:"table:endorse, do:true"`
	Id        interface{} // pk
	EndorseId interface{} // 签名id
	PoapId    interface{} // 签名徽章id
	Uid       interface{} // 发起签名的用户ID
	Text      interface{} // 签名文字
	Img       interface{} // 签名图片
	CreateAt  *gtime.Time // Created Time
	UpdateAt  *gtime.Time // Updated Time
}
