// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Endorselike is the golang structure of table endorselike for DAO operations like Where/Data.
type Endorselike struct {
	g.Meta    `orm:"table:endorselike, do:true"`
	Id        interface{} // pk
	EndorseId interface{} // 签名id
	Uid       interface{} // 发起签名的用户ID
	CreateAt  *gtime.Time // Created Time
	UpdateAt  *gtime.Time // Updated Time
}
