// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Hold is the golang structure of table hold for DAO operations like Where/Data.
type Hold struct {
	g.Meta `orm:"table:hold, do:true"`
	Uid    interface{} // User ID
	PoapId interface{} // Poap id
}
