// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Like is the golang structure of table like for DAO operations like Where/Data.
type Like struct {
	g.Meta   `orm:"table:like, do:true"`
	Id       interface{} // pk
	Uid      interface{} // User ID
	PoapId   interface{} // Poap id
	CreateAt *gtime.Time // Created Time
	UpdateAt *gtime.Time // Updated Time
}
