// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Phone is the golang structure of table phone for DAO operations like Where/Data.
type Phone struct {
	g.Meta `orm:"table:phone, do:true"`
	Phone  interface{} //
}
