// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Poap is the golang structure of table poap for DAO operations like Where/Data.
type Poap struct {
	g.Meta      `orm:"table:poap, do:true"`
	Id          interface{} // pk
	PoapId      interface{} // Poap id
	Miner       interface{} // Miner
	PoapName    interface{} // Poap name
	PoapSum     interface{} // Poap sum
	ReceiveCond interface{} // Receive condition
	CoverImg    interface{} // Cover picture
	PoapIntro   interface{} // Poap introduction
	CreateAt    *gtime.Time // Created Time
	UpdateAt    *gtime.Time // Updated Time
	CollectList interface{} //
	MintPlat    interface{} // Mint platform
	Status      interface{} // 状态 0.新建 1.正常（已铸造） 2.审核通过 3.审核不通过
	Type        interface{} // 类型  1.poap 2.头像nft 3.did
	Seriesid    interface{} //
}
