// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Poapseries is the golang structure of table poapseries for DAO operations like Where/Data.
type Poapseries struct {
	g.Meta        `orm:"table:poapseries, do:true"`
	Id            interface{} // pk
	SeriesId      interface{} // 徽章系列ID
	SeriesName    interface{} // 徽章系列名称
	SeriesType    interface{} // 徽章系列类型
	SeriesIntro   interface{} // 徽章系列简介
	SeriesNum     interface{} // 徽章系列总量
	SeriesNumLeft interface{} // 徽章系列剩余数量
	CreateAt      *gtime.Time // Created Time
	UpdateAt      *gtime.Time // Updated Time
}
