// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Poap is the golang structure of table poap for DAO operations like Where/Data.
type Poap struct {
	g.Meta           `orm:"table:poap, do:true"`
	PoapId           interface{} // Poap id
	Miner            interface{} // Miner
	PoapName         interface{} // Poap name
	PoapNumber       interface{} // Poap number
	ReceiveCondition interface{} // Receive condition
	CoverPic         interface{} // Cover picture
	PoapIntro        interface{} // Poap introduction
	FavourNumber     interface{} // Favour_number
}
