// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta       `orm:"table:user, do:true"`
	Id           interface{} // pk
	Uid          interface{} // User ID
	Username     interface{} // Username
	Password     interface{} // User Password
	Nickname     interface{} // User Nickname
	PhoneNumber  interface{} // Phone Number
	WechatNumber interface{} // Wechat Number
	InviteCode   interface{} // 邀请码
	Introduction interface{} // 自我介绍
	Avatar       []byte      // 头像
	Score        interface{} // 积分
	CreateAt     *gtime.Time // Created Time
	UpdateAt     *gtime.Time // Updated Time
}
