// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EndorseDao is the data access object for table endorse.
type EndorseDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns EndorseColumns // columns contains all the column names of Table for convenient usage.
}

// EndorseColumns defines and stores column names for table endorse.
type EndorseColumns struct {
	Id        string // pk
	EndorseId string // 签名id
	PoapId    string // 签名徽章id
	Uid       string // 发起签名的用户ID
	Text      string // 签名文字
	Img       string // 签名图片
	CreateAt  string // Created Time
	UpdateAt  string // Updated Time
}

// endorseColumns holds the columns for table endorse.
var endorseColumns = EndorseColumns{
	Id:        "id",
	EndorseId: "endorse_id",
	PoapId:    "poap_id",
	Uid:       "uid",
	Text:      "text",
	Img:       "img",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
}

// NewEndorseDao creates and returns a new DAO object for table data access.
func NewEndorseDao() *EndorseDao {
	return &EndorseDao{
		group:   "default",
		table:   "endorse",
		columns: endorseColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EndorseDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EndorseDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EndorseDao) Columns() EndorseColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EndorseDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EndorseDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EndorseDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
