// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// LikeDao is the data access object for table like.
type LikeDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns LikeColumns // columns contains all the column names of Table for convenient usage.
}

// LikeColumns defines and stores column names for table like.
type LikeColumns struct {
	Id       string // pk
	Uid      string // User ID
	PoapId   string // Poap id
	CreateAt string // Created Time
	UpdateAt string // Updated Time
}

// likeColumns holds the columns for table like.
var likeColumns = LikeColumns{
	Id:       "id",
	Uid:      "uid",
	PoapId:   "poap_id",
	CreateAt: "create_at",
	UpdateAt: "update_at",
}

// NewLikeDao creates and returns a new DAO object for table data access.
func NewLikeDao() *LikeDao {
	return &LikeDao{
		group:   "default",
		table:   "like",
		columns: likeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *LikeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *LikeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *LikeDao) Columns() LikeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *LikeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *LikeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *LikeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
