// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PhoneDao is the data access object for table phone.
type PhoneDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns PhoneColumns // columns contains all the column names of Table for convenient usage.
}

// PhoneColumns defines and stores column names for table phone.
type PhoneColumns struct {
	Phone string //
}

// phoneColumns holds the columns for table phone.
var phoneColumns = PhoneColumns{
	Phone: "phone",
}

// NewPhoneDao creates and returns a new DAO object for table data access.
func NewPhoneDao() *PhoneDao {
	return &PhoneDao{
		group:   "default",
		table:   "phone",
		columns: phoneColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PhoneDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PhoneDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PhoneDao) Columns() PhoneColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PhoneDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PhoneDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PhoneDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
