# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      #- link: "{DatabaseType}:{Name}:{YourPassword}@tcp(127.0.0.1:3306)/test"
      - link: "mysql:root:Tjz8280508@tcp(127.0.0.1:3306)/test"
        tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
