# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      #- link: "{DatabaseType}:{Name}:{YourPassword}@tcp(127.0.0.1:3306)/test"
      - link: "mysql:root:123456@tcp(118.195.238.77:3306)/wesoul"
        tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
