// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalEndorseDao is internal type for wrapping internal DAO implements.
type internalEndorseDao = *internal.EndorseDao

// endorseDao is the data access object for table endorse.
// You can define custom methods on it to extend its functionality as you wish.
type endorseDao struct {
	internalEndorseDao
}

var (
	// Endorse is globally public accessible object for table endorse operations.
	Endorse = endorseDao{
		internal.NewEndorseDao(),
	}
)

// Fill with you ideas below.
