// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalEndorselikeDao is internal type for wrapping internal DAO implements.
type internalEndorselikeDao = *internal.EndorselikeDao

// endorselikeDao is the data access object for table endorselike.
// You can define custom methods on it to extend its functionality as you wish.
type endorselikeDao struct {
	internalEndorselikeDao
}

var (
	// Endorselike is globally public accessible object for table endorselike operations.
	Endorselike = endorselikeDao{
		internal.NewEndorselikeDao(),
	}
)

// Fill with you ideas below.
