// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalOperationDao is internal type for wrapping internal DAO implements.
type internalOperationDao = *internal.OperationDao

// operationDao is the data access object for table operation.
// You can define custom methods on it to extend its functionality as you wish.
type operationDao struct {
	internalOperationDao
}

var (
	// Operation is globally public accessible object for table operation operations.
	Operation = operationDao{
		internal.NewOperationDao(),
	}
)

// Fill with you ideas below.
