// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalPhoneDao is internal type for wrapping internal DAO implements.
type internalPhoneDao = *internal.PhoneDao

// phoneDao is the data access object for table phone.
// You can define custom methods on it to extend its functionality as you wish.
type phoneDao struct {
	internalPhoneDao
}

var (
	// Phone is globally public accessible object for table phone operations.
	Phone = phoneDao{
		internal.NewPhoneDao(),
	}
)

// Fill with you ideas below.
