// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalPoapseriesDao is internal type for wrapping internal DAO implements.
type internalPoapseriesDao = *internal.PoapseriesDao

// poapseriesDao is the data access object for table poapseries.
// You can define custom methods on it to extend its functionality as you wish.
type poapseriesDao struct {
	internalPoapseriesDao
}

var (
	// Poapseries is globally public accessible object for table poapseries operations.
	Poapseries = poapseriesDao{
		internal.NewPoapseriesDao(),
	}
)

// Fill with you ideas below.
