// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalPoapDao is internal type for wrapping internal DAO implements.
type internalPoapDao = *internal.PoapDao

// poapDao is the data access object for table poap.
// You can define custom methods on it to extend its functionality as you wish.
type poapDao struct {
	internalPoapDao
}

var (
	// Poap is globally public accessible object for table poap operations.
	Poap = poapDao{
		internal.NewPoapDao(),
	}
)

// Fill with you ideas below.
