// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalPublishDao is internal type for wrapping internal DAO implements.
type internalPublishDao = *internal.PublishDao

// publishDao is the data access object for table publish.
// You can define custom methods on it to extend its functionality as you wish.
type publishDao struct {
	internalPublishDao
}

var (
	// Publish is globally public accessible object for table publish operations.
	Publish = publishDao{
		internal.NewPublishDao(),
	}
)

// Fill with you ideas below.
