// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalUserlinkDao is internal type for wrapping internal DAO implements.
type internalUserlinkDao = *internal.UserlinkDao

// userlinkDao is the data access object for table userlink.
// You can define custom methods on it to extend its functionality as you wish.
type userlinkDao struct {
	internalUserlinkDao
}

var (
	// Userlink is globally public accessible object for table userlink operations.
	Userlink = userlinkDao{
		internal.NewUserlinkDao(),
	}
)

// Fill with you ideas below.
