// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Endorselike is the golang structure for table endorselike.
type Endorselike struct {
	Id        uint        `json:"id"        ` // pk
	EndorseId string      `json:"endorseId" ` // 签名id
	Uid       string      `json:"uid"       ` // 发起签名的用户ID
	CreateAt  *gtime.Time `json:"createAt"  ` // Created Time
	UpdateAt  *gtime.Time `json:"updateAt"  ` // Updated Time
}
