// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Endorse is the golang structure for table endorse.
type Endorse struct {
	Id        uint        `json:"id"        ` // pk
	EndorseId string      `json:"endorseId" ` // 签名id
	PoapId    string      `json:"poapId"    ` // 签名徽章id
	Uid       string      `json:"uid"       ` // 发起签名的用户ID
	Text      string      `json:"text"      ` // 签名文字
	Img       string      `json:"img"       ` // 签名图片
	CreateAt  *gtime.Time `json:"createAt"  ` // Created Time
	UpdateAt  *gtime.Time `json:"updateAt"  ` // Updated Time
}
