// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Favor is the golang structure for table favor.
type Favor struct {
	Uid       string      `json:"uid"       ` // User ID
	PoapId    uint        `json:"poapId"    ` // Poap id
	FavorTime *gtime.Time `json:"favorTime" ` // Favor Time
}
