// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Follow is the golang structure for table follow.
type Follow struct {
	Id       uint        `json:"id"       ` // pk
	Followee string      `json:"followee" ` // Followee ID
	Follower string      `json:"follower" ` // Follower id
	CreateAt *gtime.Time `json:"createAt" ` // Created Time
	UpdateAt *gtime.Time `json:"updateAt" ` // Updated Time
}
