// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Hold is the golang structure for table hold.
type Hold struct {
	Uid    string `json:"uid"    ` // User ID
	PoapId uint   `json:"poapId" ` // Poap id
}
