// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Operation is the golang structure for table operation.
type Operation struct {
	Uid         string      `json:"uid"         ` // User ID
	OperateCode uint        `json:"operateCode" ` // Operate Code
	OperateTime *gtime.Time `json:"operateTime" ` // Operate Time
	Score       uint        `json:"score"       ` // Score
}
