// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Operation is the golang structure for table operation.
type Operation struct {
	Id        uint        `json:"id"        ` // pk
	Uid       string      `json:"uid"       ` // User ID
	OptType   uint        `json:"optType"   ` // Operate Type
	Score     int        `json:"score"     ` // Score
	CreateAt  *gtime.Time `json:"create_at"  ` // Created Time
	UpdateAt  *gtime.Time `json:"update_at"  ` // Updated Time
	OverdueAt *gtime.Time `json:"overdue_at" ` //
}
