// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Operation is the golang structure for table operation.
type Operation struct {
	Id       uint        `json:"id"       ` // pk
	Uid      uint        `json:"uid"      ` // User ID
	OptType  uint        `json:"optType"  ` // Operate Type
	Score    uint        `json:"score"    ` // Score
	CreateAt *gtime.Time `json:"createAt" ` // Created Time
	UpdateAt *gtime.Time `json:"updateAt" ` // Updated Time
}
