// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Phone is the golang structure for table phone.
type Phone struct {
	Phone string `json:"phone" ` //
}
