// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Poap is the golang structure for table poap.
type Poap struct {
	Id          uint        `json:"id"          ` // pk
	PoapId      string      `json:"poap_id"      ` // Poap id
	Miner       string      `json:"miner"       ` // Miner
	PoapName    string      `json:"poap_name"    ` // Poap name
	PoapSum     int         `json:"poap_sum"     ` // Poap sum
	ReceiveCond int         `json:"receive_cond" ` // Receive condition
	CoverImg    string      `json:"cover_img"    ` // Cover picture
	PoapIntro   string      `json:"poap_intro"   ` // Poap introduction
	CreateAt    *gtime.Time `json:"createAt"    ` // Created Time
	UpdateAt    *gtime.Time `json:"updateAt"    ` // Updated Time
	MintPlat int `json:"mintPlat" ` // mintPlat
	CollectList string `json:"collectList"` // Collector list
}
