// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Poapseries is the golang structure for table poapseries.
type Poapseries struct {
	Id            uint        `json:"id"            ` // pk
	SeriesId      string      `json:"seriesId"      ` // 徽章系列ID
	SeriesName    string      `json:"seriesName"    ` // 徽章系列名称
	SeriesType    int         `json:"seriesType"    ` // 徽章系列类型
	SeriesIntro   string      `json:"seriesIntro"   ` // 徽章系列简介
	SeriesNum     int         `json:"seriesNum"     ` // 徽章系列总量
	SeriesNumLeft int         `json:"seriesNumLeft" ` // 徽章系列剩余数量
	CreateAt      *gtime.Time `json:"createAt"      ` // Created Time
	UpdateAt      *gtime.Time `json:"updateAt"      ` // Updated Time
}
