// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Publish is the golang structure for table publish.
type Publish struct {
	Id           int64       `json:"id"           ` // 主键ID
	PoapId       string      `json:"poapId"       ` // Poap id
	TokenId      string      `json:"tokenId"      ` // Poap tokenId
	Status       string      `json:"status"       ` // 状态 disable:未使用 used.已使用
	No           uint64      `json:"no"           ` // 编号
	ChainStatus  int         `json:"chainStatus"  ` // 上链状态  0.未上链 1.已上链  2.上链中 3.上链失败
	ChainHash    string      `json:"chainHash"    ` // 链上hash
	IsError      int         `json:"isError"      ` // 是否异常
	ErrorMessage string      `json:"errorMessage" ` // 错误信息
	LockFlag     uint        `json:"lockFlag"     ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
