// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id           uint        `json:"id"           ` // pk
	Uid          string      `json:"uid"          ` // User ID
	Username     string      `json:"username"     ` // Username
	Password     string      `json:"password"     ` // User Password
	Nickname     string      `json:"nickname"     ` // User Nickname
	PhoneNumber  string      `json:"phoneNumber"  ` // Phone Number
	WechatNumber string      `json:"wechatNumber" ` // Wechat Number
	InviteCode   string      `json:"inviteCode"   ` // 邀请码
	Introduction string      `json:"introduction" ` // 自我介绍
	Avatar       []byte      `json:"avatar"       ` // 头像
	Score        int         `json:"score"        ` // 积分
	CreateAt     *gtime.Time `json:"createAt"     ` // Created Time
	UpdateAt     *gtime.Time `json:"updateAt"     ` // Updated Time
}
