// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Userlink is the golang structure for table userlink.
type Userlink struct {
	Uid      string `json:"uid"      ` // User ID
	Link     string `json:"link"     ` // Link
	LinkType int    `json:"linkType" ` // Link type
}
