// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Userlink is the golang structure for table userlink.
type Userlink struct {
	Id        uint        `json:"id"        ` // pk
	Uid       string      `json:"uid"       ` // User ID
	Link      string      `json:"link"      ` // Link
	LinkType  int         `json:"linkType"  ` // Link type
	CreateAt  *gtime.Time `json:"createAt"  ` // Created Time
	UpdateAt  *gtime.Time `json:"updateAt"  ` // Updated Time
	LinkTitle string      `json:"linkTitle" ` // Link Title
}
